language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
env:
  - SPHINX=">=1.3,<1.4"
  - SPHINX=">=1.4,<1.5"
  - SPHINX=">=1.5,<1.6"
  - SPHINX=">=1.6,<1.7"
install:
  # For some reason Travis' build envs have wildly different pip/setuptools
  # versions between minor Python versions, and this can cause many hilarious
  # corner packaging cases. So...
  - pip install -U pip
  # Setuptools 34+ seems to get less stable
  - pip install 'setuptools>33,<34'
  # Install dev requirements
  - pip install -r dev-requirements.txt
  # Limit Sphinx version re: test matrix
  - pip install "sphinx$SPHINX"
  # Sanity/debug-friendliness: list what got installed
  - pip list --format=columns
  # Dev tooling sanity test: can invoke list tasks?
  - inv --list
script:
  # We have no real tests at present so we just make sure installation works,
  # first off.
  - pip install .
  # Does our own dogfooding website build ok? :D
  - inv docs
  # I have this in my git pre-push hook, but contributors probably don't
  - flake8
